In [1]:
import pandas as pd

In [2]:
comparison = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy": [
        0.808,
        0.7865,
        0.861,
        0.860
    ],

    "Precision": [
        0.5891,
        0.4776,
        0.7699,
        0.7326
    ],

    "Recall": [
        0.1867,
        0.5233,
        0.4521,
        0.4914
    ],

    "F1 Score": [
        0.2836,
        0.4994,
        0.5697,
        0.5882
    ],

    "ROC AUC": [
        0.7748,
        0.6885,
        0.8545,
        0.8516
    ]
})

comparison

                 Model  Accuracy  Precision  Recall  F1 Score  ROC AUC
0  Logistic Regression    0.8080     0.5891  0.1867    0.2836   0.7748
1        Decision Tree    0.7865     0.4776  0.5233    0.4994   0.6885
2        Random Forest    0.8610     0.7699  0.4521    0.5697   0.8545
3              XGBoost    0.8600     0.7326  0.4914    0.5882   0.8516

In [4]:
comparison.sort_values(
    by="F1 Score", ascending=False
)

                 Model  Accuracy  Precision  Recall  F1 Score  ROC AUC
3              XGBoost    0.8600     0.7326  0.4914    0.5882   0.8516
2        Random Forest    0.8610     0.7699  0.4521    0.5697   0.8545
1        Decision Tree    0.7865     0.4776  0.5233    0.4994   0.6885
0  Logistic Regression    0.8080     0.5891  0.1867    0.2836   0.7748